FROM ubuntu:22.04

RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y python3 python3-pip

#RUN apt-add-repository ppa:mosquitto-dev/mosquitto-ppa && apt update &&
RUN apt-get install -y mosquitto mosquitto-clients

COPY mosquitto.conf ./

CMD ["mosquitto", "-c", "./mosquitto.conf", "-d"]
