# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.deploy_service_function import DeployServiceFunction  # noqa: F401,E501
from swagger_server.models.service_function_index import ServiceFunctionIndex  # noqa: F401,E501
from swagger_server import util


class DeployChain(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, chain_service_function_instance_name: str=None, chain_service_function_order: List[ServiceFunctionIndex]=None, service_functions: List[DeployServiceFunction]=None):  # noqa: E501
        """DeployChain - a model defined in Swagger

        :param chain_service_function_instance_name: The chain_service_function_instance_name of this DeployChain.  # noqa: E501
        :type chain_service_function_instance_name: str
        :param chain_service_function_order: The chain_service_function_order of this DeployChain.  # noqa: E501
        :type chain_service_function_order: List[ServiceFunctionIndex]
        :param service_functions: The service_functions of this DeployChain.  # noqa: E501
        :type service_functions: List[DeployServiceFunction]
        """
        self.swagger_types = {
            'chain_service_function_instance_name': str,
            'chain_service_function_order': List[ServiceFunctionIndex],
            'service_functions': List[DeployServiceFunction]
        }

        self.attribute_map = {
            'chain_service_function_instance_name': 'chain_service_function_instance_name',
            'chain_service_function_order': 'chain_service_function_order',
            'service_functions': 'service_functions'
        }
        self._chain_service_function_instance_name = chain_service_function_instance_name
        self._chain_service_function_order = chain_service_function_order
        self._service_functions = service_functions

    @classmethod
    def from_dict(cls, dikt) -> 'DeployChain':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The deployChain of this DeployChain.  # noqa: E501
        :rtype: DeployChain
        """
        return util.deserialize_model(dikt, cls)

    @property
    def chain_service_function_instance_name(self) -> str:
        """Gets the chain_service_function_instance_name of this DeployChain.


        :return: The chain_service_function_instance_name of this DeployChain.
        :rtype: str
        """
        return self._chain_service_function_instance_name

    @chain_service_function_instance_name.setter
    def chain_service_function_instance_name(self, chain_service_function_instance_name: str):
        """Sets the chain_service_function_instance_name of this DeployChain.


        :param chain_service_function_instance_name: The chain_service_function_instance_name of this DeployChain.
        :type chain_service_function_instance_name: str
        """

        self._chain_service_function_instance_name = chain_service_function_instance_name

    @property
    def chain_service_function_order(self) -> List[ServiceFunctionIndex]:
        """Gets the chain_service_function_order of this DeployChain.


        :return: The chain_service_function_order of this DeployChain.
        :rtype: List[ServiceFunctionIndex]
        """
        return self._chain_service_function_order

    @chain_service_function_order.setter
    def chain_service_function_order(self, chain_service_function_order: List[ServiceFunctionIndex]):
        """Sets the chain_service_function_order of this DeployChain.


        :param chain_service_function_order: The chain_service_function_order of this DeployChain.
        :type chain_service_function_order: List[ServiceFunctionIndex]
        """

        self._chain_service_function_order = chain_service_function_order

    @property
    def service_functions(self) -> List[DeployServiceFunction]:
        """Gets the service_functions of this DeployChain.


        :return: The service_functions of this DeployChain.
        :rtype: List[DeployServiceFunction]
        """
        return self._service_functions

    @service_functions.setter
    def service_functions(self, service_functions: List[DeployServiceFunction]):
        """Sets the service_functions of this DeployChain.


        :param service_functions: The service_functions of this DeployChain.
        :type service_functions: List[DeployServiceFunction]
        """

        self._service_functions = service_functions
