# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class NodesResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, name: str=None, location: str=None, serial: str=None):  # noqa: E501
        """NodesResponse - a model defined in Swagger

        :param id: The id of this NodesResponse.  # noqa: E501
        :type id: str
        :param name: The name of this NodesResponse.  # noqa: E501
        :type name: str
        :param location: The location of this NodesResponse.  # noqa: E501
        :type location: str
        :param serial: The serial of this NodesResponse.  # noqa: E501
        :type serial: str
        """
        self.swagger_types = {
            'id': str,
            'name': str,
            'location': str,
            'serial': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'location': 'location',
            'serial': 'serial'
        }
        self._id = id
        self._name = name
        self._location = location
        self._serial = serial

    @classmethod
    def from_dict(cls, dikt) -> 'NodesResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The nodesResponse of this NodesResponse.  # noqa: E501
        :rtype: NodesResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this NodesResponse.


        :return: The id of this NodesResponse.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this NodesResponse.


        :param id: The id of this NodesResponse.
        :type id: str
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this NodesResponse.


        :return: The name of this NodesResponse.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this NodesResponse.


        :param name: The name of this NodesResponse.
        :type name: str
        """

        self._name = name

    @property
    def location(self) -> str:
        """Gets the location of this NodesResponse.


        :return: The location of this NodesResponse.
        :rtype: str
        """
        return self._location

    @location.setter
    def location(self, location: str):
        """Sets the location of this NodesResponse.


        :param location: The location of this NodesResponse.
        :type location: str
        """

        self._location = location

    @property
    def serial(self) -> str:
        """Gets the serial of this NodesResponse.


        :return: The serial of this NodesResponse.
        :rtype: str
        """
        return self._serial

    @serial.setter
    def serial(self, serial: str):
        """Sets the serial of this NodesResponse.


        :param serial: The serial of this NodesResponse.
        :type serial: str
        """

        self._serial = serial
