apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: kostas-tandem
spec:
  ports:
    - port: 3000
      protocol: TCP
      nodePort: 31000
      targetPort: http-grafana
  selector:
    app: grafana
  type: NodePort
