#
# Generated by Elyra 3.14.3
#
import kfp
import kfp.aws
from kubernetes.client import *
from kubernetes.client.models import *


component_def_dff80db930265a7bd077ad6bdce540816a44a4db8e343e16bd178d237b60c0ff = """
name: Run a file
description: Run a Jupyter notebook or Python/R script

implementation:
  container:
    image: amancevice/pandas@sha256:f74bef70689b19d3cd610ef67227fce1c9a6ed8fa950ac2aff39ce72310d5520
    command: [sh, -c]
    args:
    - |
      sh -c "mkdir -p ./jupyter-work-dir && cd ./jupyter-work-dir"
      sh -c "echo 'Downloading https://raw.githubusercontent.com/elyra-ai/elyra/v3.14.3/elyra/kfp/bootstrapper.py' && curl --fail -H 'Cache-Control: no-cache' -L https://raw.githubusercontent.com/elyra-ai/elyra/v3.14.3/elyra/kfp/bootstrapper.py --output bootstrapper.py"
      sh -c "echo 'Downloading https://raw.githubusercontent.com/elyra-ai/elyra/v3.14.3/etc/generic/requirements-elyra.txt' && curl --fail -H 'Cache-Control: no-cache' -L https://raw.githubusercontent.com/elyra-ai/elyra/v3.14.3/etc/generic/requirements-elyra.txt --output requirements-elyra.txt"
      sh -c "python3 -m pip install  packaging && python3 -m pip freeze > requirements-current.txt && python3 bootstrapper.py --pipeline-name 'tandem' --cos-endpoint 'http://minio.kubeflow:9000' --cos-bucket 'mlpipeline' --cos-directory 'tandem-0419072150' --cos-dependencies-archive 'core_pass-8c93bc6a-77d7-4530-9ca9-76ec0f612c23.tar.gz' --file 'tandem-pipeline/core_pass.py' --outputs 'token.json' "
"""

factory_dff80db930265a7bd077ad6bdce540816a44a4db8e343e16bd178d237b60c0ff = (
    kfp.components.load_component_from_text(
        component_def_dff80db930265a7bd077ad6bdce540816a44a4db8e343e16bd178d237b60c0ff
    )
)

component_def_5bd9f8dce0eb7ec3fdd0333f66bcc1ee9760a958456563405d8d5838e7e48403 = """
name: Run a file
description: Run a Jupyter notebook or Python/R script

implementation:
  container:
    image: amancevice/pandas@sha256:f74bef70689b19d3cd610ef67227fce1c9a6ed8fa950ac2aff39ce72310d5520
    command: [sh, -c]
    args:
    - |
      sh -c "mkdir -p ./jupyter-work-dir && cd ./jupyter-work-dir"
      sh -c "echo 'Downloading https://raw.githubusercontent.com/elyra-ai/elyra/v3.14.3/elyra/kfp/bootstrapper.py' && curl --fail -H 'Cache-Control: no-cache' -L https://raw.githubusercontent.com/elyra-ai/elyra/v3.14.3/elyra/kfp/bootstrapper.py --output bootstrapper.py"
      sh -c "echo 'Downloading https://raw.githubusercontent.com/elyra-ai/elyra/v3.14.3/etc/generic/requirements-elyra.txt' && curl --fail -H 'Cache-Control: no-cache' -L https://raw.githubusercontent.com/elyra-ai/elyra/v3.14.3/etc/generic/requirements-elyra.txt --output requirements-elyra.txt"
      sh -c "python3 -m pip install  packaging && python3 -m pip freeze > requirements-current.txt && python3 bootstrapper.py --pipeline-name 'tandem' --cos-endpoint 'http://minio.kubeflow:9000' --cos-bucket 'mlpipeline' --cos-directory 'tandem-0419072150' --cos-dependencies-archive 'iot_device-f0a5108a-48ab-43e6-bcc1-3a26e496b26a.tar.gz' --file 'tandem-pipeline/iot_device.py' --inputs 'token.json' "
"""

factory_5bd9f8dce0eb7ec3fdd0333f66bcc1ee9760a958456563405d8d5838e7e48403 = (
    kfp.components.load_component_from_text(
        component_def_5bd9f8dce0eb7ec3fdd0333f66bcc1ee9760a958456563405d8d5838e7e48403
    )
)

component_def_d9429e8eeabafef38f3ce7bf69b64d34d5edbdac2bf9a5b9e311c1d437103562 = """
name: Run a file
description: Run a Jupyter notebook or Python/R script

implementation:
  container:
    image: amancevice/pandas@sha256:f74bef70689b19d3cd610ef67227fce1c9a6ed8fa950ac2aff39ce72310d5520
    command: [sh, -c]
    args:
    - |
      sh -c "mkdir -p ./jupyter-work-dir && cd ./jupyter-work-dir"
      sh -c "echo 'Downloading https://raw.githubusercontent.com/elyra-ai/elyra/v3.14.3/elyra/kfp/bootstrapper.py' && curl --fail -H 'Cache-Control: no-cache' -L https://raw.githubusercontent.com/elyra-ai/elyra/v3.14.3/elyra/kfp/bootstrapper.py --output bootstrapper.py"
      sh -c "echo 'Downloading https://raw.githubusercontent.com/elyra-ai/elyra/v3.14.3/etc/generic/requirements-elyra.txt' && curl --fail -H 'Cache-Control: no-cache' -L https://raw.githubusercontent.com/elyra-ai/elyra/v3.14.3/etc/generic/requirements-elyra.txt --output requirements-elyra.txt"
      sh -c "python3 -m pip install  packaging && python3 -m pip freeze > requirements-current.txt && python3 bootstrapper.py --pipeline-name 'tandem' --cos-endpoint 'http://minio.kubeflow:9000' --cos-bucket 'mlpipeline' --cos-directory 'tandem-0419072150' --cos-dependencies-archive 'custom_paas-62a33a47-6d12-41fc-9f65-0d09a3921532.tar.gz' --file 'tandem-pipeline/custom_paas.py' --inputs 'token.json' --outputs 'custom_paas.json' "
"""

factory_d9429e8eeabafef38f3ce7bf69b64d34d5edbdac2bf9a5b9e311c1d437103562 = (
    kfp.components.load_component_from_text(
        component_def_d9429e8eeabafef38f3ce7bf69b64d34d5edbdac2bf9a5b9e311c1d437103562
    )
)

component_def_db650a1ae891269220583cb15c477ea669a7f44ec663f715dd82716b512e09c7 = """
name: Run a file
description: Run a Jupyter notebook or Python/R script

implementation:
  container:
    image: amancevice/pandas@sha256:f74bef70689b19d3cd610ef67227fce1c9a6ed8fa950ac2aff39ce72310d5520
    command: [sh, -c]
    args:
    - |
      sh -c "mkdir -p ./jupyter-work-dir && cd ./jupyter-work-dir"
      sh -c "echo 'Downloading https://raw.githubusercontent.com/elyra-ai/elyra/v3.14.3/elyra/kfp/bootstrapper.py' && curl --fail -H 'Cache-Control: no-cache' -L https://raw.githubusercontent.com/elyra-ai/elyra/v3.14.3/elyra/kfp/bootstrapper.py --output bootstrapper.py"
      sh -c "echo 'Downloading https://raw.githubusercontent.com/elyra-ai/elyra/v3.14.3/etc/generic/requirements-elyra.txt' && curl --fail -H 'Cache-Control: no-cache' -L https://raw.githubusercontent.com/elyra-ai/elyra/v3.14.3/etc/generic/requirements-elyra.txt --output requirements-elyra.txt"
      sh -c "python3 -m pip install  packaging && python3 -m pip freeze > requirements-current.txt && python3 bootstrapper.py --pipeline-name 'tandem' --cos-endpoint 'http://minio.kubeflow:9000' --cos-bucket 'mlpipeline' --cos-directory 'tandem-0419072150' --cos-dependencies-archive 'edgex_mqtt_writer-3f0d5522-1d0c-462b-99e2-ad37ae160938.tar.gz' --file 'tandem-pipeline/edgex_mqtt_writer.py' --inputs 'custom_paas.json;token.json' "
"""

factory_db650a1ae891269220583cb15c477ea669a7f44ec663f715dd82716b512e09c7 = (
    kfp.components.load_component_from_text(
        component_def_db650a1ae891269220583cb15c477ea669a7f44ec663f715dd82716b512e09c7
    )
)

component_def_07bc3dca8a1ba8a2b62a634ffafc55c694f4001414938d1c760281f4cc7cdfe7 = """
name: Run a file
description: Run a Jupyter notebook or Python/R script

implementation:
  container:
    image: amancevice/pandas@sha256:f74bef70689b19d3cd610ef67227fce1c9a6ed8fa950ac2aff39ce72310d5520
    command: [sh, -c]
    args:
    - |
      sh -c "mkdir -p ./jupyter-work-dir && cd ./jupyter-work-dir"
      sh -c "echo 'Downloading https://raw.githubusercontent.com/elyra-ai/elyra/v3.14.3/elyra/kfp/bootstrapper.py' && curl --fail -H 'Cache-Control: no-cache' -L https://raw.githubusercontent.com/elyra-ai/elyra/v3.14.3/elyra/kfp/bootstrapper.py --output bootstrapper.py"
      sh -c "echo 'Downloading https://raw.githubusercontent.com/elyra-ai/elyra/v3.14.3/etc/generic/requirements-elyra.txt' && curl --fail -H 'Cache-Control: no-cache' -L https://raw.githubusercontent.com/elyra-ai/elyra/v3.14.3/etc/generic/requirements-elyra.txt --output requirements-elyra.txt"
      sh -c "python3 -m pip install  packaging && python3 -m pip freeze > requirements-current.txt && python3 bootstrapper.py --pipeline-name 'tandem' --cos-endpoint 'http://minio.kubeflow:9000' --cos-bucket 'mlpipeline' --cos-directory 'tandem-0419072150' --cos-dependencies-archive 'webhook-d5435ba0-0484-4949-bd10-f9406bb83dc1.tar.gz' --file 'tandem-pipeline/webhook.py' --inputs 'custom_paas.json;token.json' "
"""

factory_07bc3dca8a1ba8a2b62a634ffafc55c694f4001414938d1c760281f4cc7cdfe7 = (
    kfp.components.load_component_from_text(
        component_def_07bc3dca8a1ba8a2b62a634ffafc55c694f4001414938d1c760281f4cc7cdfe7
    )
)


@kfp.dsl.pipeline(name="tandem")
def generated_pipeline():
    # Task for node 'core_pass'
    task_8c93bc6a_77d7_4530_9ca9_76ec0f612c23 = (
        factory_dff80db930265a7bd077ad6bdce540816a44a4db8e343e16bd178d237b60c0ff()
    )

    task_8c93bc6a_77d7_4530_9ca9_76ec0f612c23.output_artifact_paths[
        "mlpipeline-metrics"
    ] = "/tmp/mlpipeline-metrics.json"
    task_8c93bc6a_77d7_4530_9ca9_76ec0f612c23.output_artifact_paths[
        "mlpipeline-ui-metadata"
    ] = "/tmp/mlpipeline-ui-metadata.json"

    task_8c93bc6a_77d7_4530_9ca9_76ec0f612c23.set_display_name("core_pass")

    task_8c93bc6a_77d7_4530_9ca9_76ec0f612c23.add_pod_annotation(
        "elyra/node-user-doc", """check availability and claim core paas (EdgeX)"""
    )

    task_8c93bc6a_77d7_4530_9ca9_76ec0f612c23.add_env_variable(
        V1EnvVar(name="TOKEN_FILE", value="token.json")
    )

    task_8c93bc6a_77d7_4530_9ca9_76ec0f612c23.add_env_variable(
        V1EnvVar(name="CORE_PAAS", value="edgex")
    )

    task_8c93bc6a_77d7_4530_9ca9_76ec0f612c23.add_env_variable(
        V1EnvVar(name="ELYRA_RUNTIME_ENV", value="kfp")
    )

    task_8c93bc6a_77d7_4530_9ca9_76ec0f612c23.add_env_variable(
        V1EnvVar(name="AWS_ACCESS_KEY_ID", value="minio")
    )

    task_8c93bc6a_77d7_4530_9ca9_76ec0f612c23.add_env_variable(
        V1EnvVar(name="AWS_SECRET_ACCESS_KEY", value="6GY3KXAKXE0XHU71CY0Y98C7PGMWVW")
    )

    task_8c93bc6a_77d7_4530_9ca9_76ec0f612c23.add_env_variable(
        V1EnvVar(name="ELYRA_ENABLE_PIPELINE_INFO", value="True")
    )

    task_8c93bc6a_77d7_4530_9ca9_76ec0f612c23.add_env_variable(
        V1EnvVar(name="ELYRA_WRITABLE_CONTAINER_DIR", value="/tmp")
    )

    task_8c93bc6a_77d7_4530_9ca9_76ec0f612c23.add_env_variable(
        V1EnvVar(name="ELYRA_RUN_NAME", value="{{workflow.uid}}")
    )

    task_8c93bc6a_77d7_4530_9ca9_76ec0f612c23.add_pod_label(
        "elyra/node-type", "notebook-script"
    )

    task_8c93bc6a_77d7_4530_9ca9_76ec0f612c23.add_pod_label(
        "elyra/pipeline-name", "tandem"
    )

    task_8c93bc6a_77d7_4530_9ca9_76ec0f612c23.add_pod_label(
        "elyra/pipeline-version", ""
    )

    task_8c93bc6a_77d7_4530_9ca9_76ec0f612c23.add_pod_label("elyra/experiment-name", "")

    task_8c93bc6a_77d7_4530_9ca9_76ec0f612c23.add_pod_label(
        "elyra/node-name", "core_pass"
    )

    task_8c93bc6a_77d7_4530_9ca9_76ec0f612c23.add_pod_annotation(
        "elyra/node-file-name", """tandem-pipeline/core_pass.py"""
    )

    task_8c93bc6a_77d7_4530_9ca9_76ec0f612c23.add_pod_annotation(
        "elyra/pipeline-source", """tandem.pipeline"""
    )

    # Task for node 'iot_device'
    task_f0a5108a_48ab_43e6_bcc1_3a26e496b26a = (
        factory_5bd9f8dce0eb7ec3fdd0333f66bcc1ee9760a958456563405d8d5838e7e48403()
    )

    task_f0a5108a_48ab_43e6_bcc1_3a26e496b26a.output_artifact_paths[
        "mlpipeline-metrics"
    ] = "/tmp/mlpipeline-metrics.json"
    task_f0a5108a_48ab_43e6_bcc1_3a26e496b26a.output_artifact_paths[
        "mlpipeline-ui-metadata"
    ] = "/tmp/mlpipeline-ui-metadata.json"

    task_f0a5108a_48ab_43e6_bcc1_3a26e496b26a.set_display_name("iot_device")

    task_f0a5108a_48ab_43e6_bcc1_3a26e496b26a.add_pod_annotation(
        "elyra/node-user-doc", """Add an iot device"""
    )

    task_f0a5108a_48ab_43e6_bcc1_3a26e496b26a.add_env_variable(
        V1EnvVar(name="TOKEN_FILE", value="token.json")
    )

    task_f0a5108a_48ab_43e6_bcc1_3a26e496b26a.add_env_variable(
        V1EnvVar(name="DEVICE_NAME", value="mytandemdevice")
    )

    task_f0a5108a_48ab_43e6_bcc1_3a26e496b26a.add_env_variable(
        V1EnvVar(name="VALUES_FILE", value="values.json")
    )

    task_f0a5108a_48ab_43e6_bcc1_3a26e496b26a.add_env_variable(
        V1EnvVar(name="ELYRA_RUNTIME_ENV", value="kfp")
    )

    task_f0a5108a_48ab_43e6_bcc1_3a26e496b26a.add_env_variable(
        V1EnvVar(name="AWS_ACCESS_KEY_ID", value="minio")
    )

    task_f0a5108a_48ab_43e6_bcc1_3a26e496b26a.add_env_variable(
        V1EnvVar(name="AWS_SECRET_ACCESS_KEY", value="6GY3KXAKXE0XHU71CY0Y98C7PGMWVW")
    )

    task_f0a5108a_48ab_43e6_bcc1_3a26e496b26a.add_env_variable(
        V1EnvVar(name="ELYRA_ENABLE_PIPELINE_INFO", value="True")
    )

    task_f0a5108a_48ab_43e6_bcc1_3a26e496b26a.add_env_variable(
        V1EnvVar(name="ELYRA_WRITABLE_CONTAINER_DIR", value="/tmp")
    )

    task_f0a5108a_48ab_43e6_bcc1_3a26e496b26a.add_env_variable(
        V1EnvVar(name="ELYRA_RUN_NAME", value="{{workflow.uid}}")
    )

    task_f0a5108a_48ab_43e6_bcc1_3a26e496b26a.add_pod_label(
        "elyra/node-type", "notebook-script"
    )

    task_f0a5108a_48ab_43e6_bcc1_3a26e496b26a.add_pod_label(
        "elyra/pipeline-name", "tandem"
    )

    task_f0a5108a_48ab_43e6_bcc1_3a26e496b26a.add_pod_label(
        "elyra/pipeline-version", ""
    )

    task_f0a5108a_48ab_43e6_bcc1_3a26e496b26a.add_pod_label("elyra/experiment-name", "")

    task_f0a5108a_48ab_43e6_bcc1_3a26e496b26a.add_pod_label(
        "elyra/node-name", "iot_device"
    )

    task_f0a5108a_48ab_43e6_bcc1_3a26e496b26a.add_pod_annotation(
        "elyra/node-file-name", """tandem-pipeline/iot_device.py"""
    )

    task_f0a5108a_48ab_43e6_bcc1_3a26e496b26a.add_pod_annotation(
        "elyra/pipeline-source", """tandem.pipeline"""
    )

    task_f0a5108a_48ab_43e6_bcc1_3a26e496b26a.after(
        task_8c93bc6a_77d7_4530_9ca9_76ec0f612c23
    )

    # Task for node 'custom_paas'
    task_62a33a47_6d12_41fc_9f65_0d09a3921532 = (
        factory_d9429e8eeabafef38f3ce7bf69b64d34d5edbdac2bf9a5b9e311c1d437103562()
    )

    task_62a33a47_6d12_41fc_9f65_0d09a3921532.output_artifact_paths[
        "mlpipeline-metrics"
    ] = "/tmp/mlpipeline-metrics.json"
    task_62a33a47_6d12_41fc_9f65_0d09a3921532.output_artifact_paths[
        "mlpipeline-ui-metadata"
    ] = "/tmp/mlpipeline-ui-metadata.json"

    task_62a33a47_6d12_41fc_9f65_0d09a3921532.set_display_name("custom_paas")

    task_62a33a47_6d12_41fc_9f65_0d09a3921532.add_pod_annotation(
        "elyra/node-user-doc", """Select and deploy a custom PaaS."""
    )

    task_62a33a47_6d12_41fc_9f65_0d09a3921532.add_env_variable(
        V1EnvVar(name="TOKEN_FILE", value="token.json")
    )

    task_62a33a47_6d12_41fc_9f65_0d09a3921532.add_env_variable(
        V1EnvVar(name="PAAS_CUSTOM_SERVICE_NAME", value="iotmonitoring")
    )

    task_62a33a47_6d12_41fc_9f65_0d09a3921532.add_env_variable(
        V1EnvVar(name="AUTOSCALING_TYPE", value="minimize_cost")
    )

    task_62a33a47_6d12_41fc_9f65_0d09a3921532.add_env_variable(
        V1EnvVar(name="COUNT_MIN", value="1")
    )

    task_62a33a47_6d12_41fc_9f65_0d09a3921532.add_env_variable(
        V1EnvVar(name="COUNT_MAX", value="1")
    )

    task_62a33a47_6d12_41fc_9f65_0d09a3921532.add_env_variable(
        V1EnvVar(name="LOCATION", value="Peania_Athens_19002")
    )

    task_62a33a47_6d12_41fc_9f65_0d09a3921532.add_env_variable(
        V1EnvVar(name="ALL_NODE_PORTS", value="True")
    )

    task_62a33a47_6d12_41fc_9f65_0d09a3921532.add_env_variable(
        V1EnvVar(name="PAAS_CUSTOM_INSTANCE_NAME", value="tandemtest")
    )

    task_62a33a47_6d12_41fc_9f65_0d09a3921532.add_env_variable(
        V1EnvVar(name="ELYRA_RUNTIME_ENV", value="kfp")
    )

    task_62a33a47_6d12_41fc_9f65_0d09a3921532.add_env_variable(
        V1EnvVar(name="AWS_ACCESS_KEY_ID", value="minio")
    )

    task_62a33a47_6d12_41fc_9f65_0d09a3921532.add_env_variable(
        V1EnvVar(name="AWS_SECRET_ACCESS_KEY", value="6GY3KXAKXE0XHU71CY0Y98C7PGMWVW")
    )

    task_62a33a47_6d12_41fc_9f65_0d09a3921532.add_env_variable(
        V1EnvVar(name="ELYRA_ENABLE_PIPELINE_INFO", value="True")
    )

    task_62a33a47_6d12_41fc_9f65_0d09a3921532.add_env_variable(
        V1EnvVar(name="ELYRA_WRITABLE_CONTAINER_DIR", value="/tmp")
    )

    task_62a33a47_6d12_41fc_9f65_0d09a3921532.add_env_variable(
        V1EnvVar(name="ELYRA_RUN_NAME", value="{{workflow.uid}}")
    )

    task_62a33a47_6d12_41fc_9f65_0d09a3921532.add_pod_label(
        "elyra/node-type", "notebook-script"
    )

    task_62a33a47_6d12_41fc_9f65_0d09a3921532.add_pod_label(
        "elyra/pipeline-name", "tandem"
    )

    task_62a33a47_6d12_41fc_9f65_0d09a3921532.add_pod_label(
        "elyra/pipeline-version", ""
    )

    task_62a33a47_6d12_41fc_9f65_0d09a3921532.add_pod_label("elyra/experiment-name", "")

    task_62a33a47_6d12_41fc_9f65_0d09a3921532.add_pod_label(
        "elyra/node-name", "custom_paas"
    )

    task_62a33a47_6d12_41fc_9f65_0d09a3921532.add_pod_annotation(
        "elyra/node-file-name", """tandem-pipeline/custom_paas.py"""
    )

    task_62a33a47_6d12_41fc_9f65_0d09a3921532.add_pod_annotation(
        "elyra/pipeline-source", """tandem.pipeline"""
    )

    task_62a33a47_6d12_41fc_9f65_0d09a3921532.after(
        task_8c93bc6a_77d7_4530_9ca9_76ec0f612c23
    )

    # Task for node 'edgex_mqtt_writer'
    task_3f0d5522_1d0c_462b_99e2_ad37ae160938 = (
        factory_db650a1ae891269220583cb15c477ea669a7f44ec663f715dd82716b512e09c7()
    )

    task_3f0d5522_1d0c_462b_99e2_ad37ae160938.output_artifact_paths[
        "mlpipeline-metrics"
    ] = "/tmp/mlpipeline-metrics.json"
    task_3f0d5522_1d0c_462b_99e2_ad37ae160938.output_artifact_paths[
        "mlpipeline-ui-metadata"
    ] = "/tmp/mlpipeline-ui-metadata.json"

    task_3f0d5522_1d0c_462b_99e2_ad37ae160938.set_display_name("edgex_mqtt_writer")

    task_3f0d5522_1d0c_462b_99e2_ad37ae160938.add_pod_annotation(
        "elyra/node-user-doc",
        """Interfacing between the core (EdgeX) and custom PaaS, to retrieve metrics for the specific device""",
    )

    task_3f0d5522_1d0c_462b_99e2_ad37ae160938.add_env_variable(
        V1EnvVar(name="TOKEN_FILE", value="token.json")
    )

    task_3f0d5522_1d0c_462b_99e2_ad37ae160938.add_env_variable(
        V1EnvVar(name="CUSTOM_PAAS_FILE", value="custom_paas.json")
    )

    task_3f0d5522_1d0c_462b_99e2_ad37ae160938.add_env_variable(
        V1EnvVar(name="ELYRA_RUNTIME_ENV", value="kfp")
    )

    task_3f0d5522_1d0c_462b_99e2_ad37ae160938.add_env_variable(
        V1EnvVar(name="AWS_ACCESS_KEY_ID", value="minio")
    )

    task_3f0d5522_1d0c_462b_99e2_ad37ae160938.add_env_variable(
        V1EnvVar(name="AWS_SECRET_ACCESS_KEY", value="6GY3KXAKXE0XHU71CY0Y98C7PGMWVW")
    )

    task_3f0d5522_1d0c_462b_99e2_ad37ae160938.add_env_variable(
        V1EnvVar(name="ELYRA_ENABLE_PIPELINE_INFO", value="True")
    )

    task_3f0d5522_1d0c_462b_99e2_ad37ae160938.add_env_variable(
        V1EnvVar(name="ELYRA_WRITABLE_CONTAINER_DIR", value="/tmp")
    )

    task_3f0d5522_1d0c_462b_99e2_ad37ae160938.add_env_variable(
        V1EnvVar(name="ELYRA_RUN_NAME", value="{{workflow.uid}}")
    )

    task_3f0d5522_1d0c_462b_99e2_ad37ae160938.add_pod_label(
        "elyra/node-type", "notebook-script"
    )

    task_3f0d5522_1d0c_462b_99e2_ad37ae160938.add_pod_label(
        "elyra/pipeline-name", "tandem"
    )

    task_3f0d5522_1d0c_462b_99e2_ad37ae160938.add_pod_label(
        "elyra/pipeline-version", ""
    )

    task_3f0d5522_1d0c_462b_99e2_ad37ae160938.add_pod_label("elyra/experiment-name", "")

    task_3f0d5522_1d0c_462b_99e2_ad37ae160938.add_pod_label(
        "elyra/node-name", "edgex_mqtt_writer"
    )

    task_3f0d5522_1d0c_462b_99e2_ad37ae160938.add_pod_annotation(
        "elyra/node-file-name", """tandem-pipeline/edgex_mqtt_writer.py"""
    )

    task_3f0d5522_1d0c_462b_99e2_ad37ae160938.add_pod_annotation(
        "elyra/pipeline-source", """tandem.pipeline"""
    )

    task_3f0d5522_1d0c_462b_99e2_ad37ae160938.after(
        task_62a33a47_6d12_41fc_9f65_0d09a3921532
    )

    # Task for node 'webhook'
    task_d5435ba0_0484_4949_bd10_f9406bb83dc1 = (
        factory_07bc3dca8a1ba8a2b62a634ffafc55c694f4001414938d1c760281f4cc7cdfe7()
    )

    task_d5435ba0_0484_4949_bd10_f9406bb83dc1.output_artifact_paths[
        "mlpipeline-metrics"
    ] = "/tmp/mlpipeline-metrics.json"
    task_d5435ba0_0484_4949_bd10_f9406bb83dc1.output_artifact_paths[
        "mlpipeline-ui-metadata"
    ] = "/tmp/mlpipeline-ui-metadata.json"

    task_d5435ba0_0484_4949_bd10_f9406bb83dc1.set_display_name("webhook")

    task_d5435ba0_0484_4949_bd10_f9406bb83dc1.add_pod_annotation(
        "elyra/node-user-doc", """Deploy an EventSource and a Sensor"""
    )

    task_d5435ba0_0484_4949_bd10_f9406bb83dc1.add_env_variable(
        V1EnvVar(name="TOKEN_FILE", value="token.json")
    )

    task_d5435ba0_0484_4949_bd10_f9406bb83dc1.add_env_variable(
        V1EnvVar(name="EVENT_NAME", value="notification")
    )

    task_d5435ba0_0484_4949_bd10_f9406bb83dc1.add_env_variable(
        V1EnvVar(name="IMAGE", value="johnkalogero/notify:v0.2")
    )

    task_d5435ba0_0484_4949_bd10_f9406bb83dc1.add_env_variable(
        V1EnvVar(name="CUSTOM_PAAS_FILE", value="custom_paas.json")
    )

    task_d5435ba0_0484_4949_bd10_f9406bb83dc1.add_env_variable(
        V1EnvVar(name="ELYRA_RUNTIME_ENV", value="kfp")
    )

    task_d5435ba0_0484_4949_bd10_f9406bb83dc1.add_env_variable(
        V1EnvVar(name="AWS_ACCESS_KEY_ID", value="minio")
    )

    task_d5435ba0_0484_4949_bd10_f9406bb83dc1.add_env_variable(
        V1EnvVar(name="AWS_SECRET_ACCESS_KEY", value="6GY3KXAKXE0XHU71CY0Y98C7PGMWVW")
    )

    task_d5435ba0_0484_4949_bd10_f9406bb83dc1.add_env_variable(
        V1EnvVar(name="ELYRA_ENABLE_PIPELINE_INFO", value="True")
    )

    task_d5435ba0_0484_4949_bd10_f9406bb83dc1.add_env_variable(
        V1EnvVar(name="ELYRA_WRITABLE_CONTAINER_DIR", value="/tmp")
    )

    task_d5435ba0_0484_4949_bd10_f9406bb83dc1.add_env_variable(
        V1EnvVar(name="ELYRA_RUN_NAME", value="{{workflow.uid}}")
    )

    task_d5435ba0_0484_4949_bd10_f9406bb83dc1.add_pod_label(
        "elyra/node-type", "notebook-script"
    )

    task_d5435ba0_0484_4949_bd10_f9406bb83dc1.add_pod_label(
        "elyra/pipeline-name", "tandem"
    )

    task_d5435ba0_0484_4949_bd10_f9406bb83dc1.add_pod_label(
        "elyra/pipeline-version", ""
    )

    task_d5435ba0_0484_4949_bd10_f9406bb83dc1.add_pod_label("elyra/experiment-name", "")

    task_d5435ba0_0484_4949_bd10_f9406bb83dc1.add_pod_label(
        "elyra/node-name", "webhook"
    )

    task_d5435ba0_0484_4949_bd10_f9406bb83dc1.add_pod_annotation(
        "elyra/node-file-name", """tandem-pipeline/webhook.py"""
    )

    task_d5435ba0_0484_4949_bd10_f9406bb83dc1.add_pod_annotation(
        "elyra/pipeline-source", """tandem.pipeline"""
    )

    task_d5435ba0_0484_4949_bd10_f9406bb83dc1.after(
        task_f0a5108a_48ab_43e6_bcc1_3a26e496b26a
    )

    task_d5435ba0_0484_4949_bd10_f9406bb83dc1.after(
        task_3f0d5522_1d0c_462b_99e2_ad37ae160938
    )


if __name__ == "__main__":
    from pathlib import Path

    kfp.compiler.Compiler().compile(
        pipeline_func=generated_pipeline,
        package_path=Path(__file__).with_suffix(".yaml").name,
    )
