# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class EndPointInfoUris(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, uris: List[str]=None):  # noqa: E501
        """EndPointInfoUris - a model defined in Swagger

        :param uris: The uris of this EndPointInfoUris.  # noqa: E501
        :type uris: List[str]
        """
        self.swagger_types = {
            'uris': List[str]
        }

        self.attribute_map = {
            'uris': 'uris'
        }
        self._uris = uris

    @classmethod
    def from_dict(cls, dikt) -> 'EndPointInfoUris':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EndPointInfo.Uris of this EndPointInfoUris.  # noqa: E501
        :rtype: EndPointInfoUris
        """
        return util.deserialize_model(dikt, cls)

    @property
    def uris(self) -> List[str]:
        """Gets the uris of this EndPointInfoUris.


        :return: The uris of this EndPointInfoUris.
        :rtype: List[str]
        """
        return self._uris

    @uris.setter
    def uris(self, uris: List[str]):
        """Sets the uris of this EndPointInfoUris.


        :param uris: The uris of this EndPointInfoUris.
        :type uris: List[str]
        """
        if uris is None:
            raise ValueError("Invalid value for `uris`, must not be `None`")  # noqa: E501

        self._uris = uris
