# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.service_state import ServiceState  # noqa: F401,E501
from swagger_server import util


class ServiceLivenessUpdate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, state: ServiceState=None):  # noqa: E501
        """ServiceLivenessUpdate - a model defined in Swagger

        :param state: The state of this ServiceLivenessUpdate.  # noqa: E501
        :type state: ServiceState
        """
        self.swagger_types = {
            'state': ServiceState
        }

        self.attribute_map = {
            'state': 'state'
        }
        self._state = state

    @classmethod
    def from_dict(cls, dikt) -> 'ServiceLivenessUpdate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ServiceLivenessUpdate of this ServiceLivenessUpdate.  # noqa: E501
        :rtype: ServiceLivenessUpdate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def state(self) -> ServiceState:
        """Gets the state of this ServiceLivenessUpdate.


        :return: The state of this ServiceLivenessUpdate.
        :rtype: ServiceState
        """
        return self._state

    @state.setter
    def state(self, state: ServiceState):
        """Sets the state of this ServiceLivenessUpdate.


        :param state: The state of this ServiceLivenessUpdate.
        :type state: ServiceState
        """
        if state is None:
            raise ValueError("Invalid value for `state`, must not be `None`")  # noqa: E501

        self._state = state
