# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AddIotDeviceLocation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, address: str=None, lat: float=None, long: float=None):  # noqa: E501
        """AddIotDeviceLocation - a model defined in Swagger

        :param address: The address of this AddIotDeviceLocation.  # noqa: E501
        :type address: str
        :param lat: The lat of this AddIotDeviceLocation.  # noqa: E501
        :type lat: float
        :param long: The long of this AddIotDeviceLocation.  # noqa: E501
        :type long: float
        """
        self.swagger_types = {
            'address': str,
            'lat': float,
            'long': float
        }

        self.attribute_map = {
            'address': 'address',
            'lat': 'lat',
            'long': 'long'
        }
        self._address = address
        self._lat = lat
        self._long = long

    @classmethod
    def from_dict(cls, dikt) -> 'AddIotDeviceLocation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The addIotDevice_location of this AddIotDeviceLocation.  # noqa: E501
        :rtype: AddIotDeviceLocation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def address(self) -> str:
        """Gets the address of this AddIotDeviceLocation.


        :return: The address of this AddIotDeviceLocation.
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address: str):
        """Sets the address of this AddIotDeviceLocation.


        :param address: The address of this AddIotDeviceLocation.
        :type address: str
        """

        self._address = address

    @property
    def lat(self) -> float:
        """Gets the lat of this AddIotDeviceLocation.


        :return: The lat of this AddIotDeviceLocation.
        :rtype: float
        """
        return self._lat

    @lat.setter
    def lat(self, lat: float):
        """Sets the lat of this AddIotDeviceLocation.


        :param lat: The lat of this AddIotDeviceLocation.
        :type lat: float
        """

        self._lat = lat

    @property
    def long(self) -> float:
        """Gets the long of this AddIotDeviceLocation.


        :return: The long of this AddIotDeviceLocation.
        :rtype: float
        """
        return self._long

    @long.setter
    def long(self, long: float):
        """Sets the long of this AddIotDeviceLocation.


        :param long: The long of this AddIotDeviceLocation.
        :type long: float
        """

        self._long = long
