# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class IotValue(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, description: str=None, type: str=None, min: int=None, max: int=None):  # noqa: E501
        """IotValue - a model defined in Swagger

        :param name: The name of this IotValue.  # noqa: E501
        :type name: str
        :param description: The description of this IotValue.  # noqa: E501
        :type description: str
        :param type: The type of this IotValue.  # noqa: E501
        :type type: str
        :param min: The min of this IotValue.  # noqa: E501
        :type min: int
        :param max: The max of this IotValue.  # noqa: E501
        :type max: int
        """
        self.swagger_types = {
            'name': str,
            'description': str,
            'type': str,
            'min': int,
            'max': int
        }

        self.attribute_map = {
            'name': 'name',
            'description': 'description',
            'type': 'type',
            'min': 'min',
            'max': 'max'
        }
        self._name = name
        self._description = description
        self._type = type
        self._min = min
        self._max = max

    @classmethod
    def from_dict(cls, dikt) -> 'IotValue':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The iotValue of this IotValue.  # noqa: E501
        :rtype: IotValue
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this IotValue.


        :return: The name of this IotValue.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this IotValue.


        :param name: The name of this IotValue.
        :type name: str
        """

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this IotValue.


        :return: The description of this IotValue.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this IotValue.


        :param description: The description of this IotValue.
        :type description: str
        """

        self._description = description

    @property
    def type(self) -> str:
        """Gets the type of this IotValue.


        :return: The type of this IotValue.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this IotValue.


        :param type: The type of this IotValue.
        :type type: str
        """

        self._type = type

    @property
    def min(self) -> int:
        """Gets the min of this IotValue.


        :return: The min of this IotValue.
        :rtype: int
        """
        return self._min

    @min.setter
    def min(self, min: int):
        """Sets the min of this IotValue.


        :param min: The min of this IotValue.
        :type min: int
        """

        self._min = min

    @property
    def max(self) -> int:
        """Gets the max of this IotValue.


        :return: The max of this IotValue.
        :rtype: int
        """
        return self._max

    @max.setter
    def max(self, max: int):
        """Sets the max of this IotValue.


        :param max: The max of this IotValue.
        :type max: int
        """

        self._max = max
