# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LocationPaasDeploy(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, service_function_name: str=None, location: str=None):  # noqa: E501
        """LocationPaasDeploy - a model defined in Swagger

        :param service_function_name: The service_function_name of this LocationPaasDeploy.  # noqa: E501
        :type service_function_name: str
        :param location: The location of this LocationPaasDeploy.  # noqa: E501
        :type location: str
        """
        self.swagger_types = {
            'service_function_name': str,
            'location': str
        }

        self.attribute_map = {
            'service_function_name': 'service_function_name',
            'location': 'location'
        }
        self._service_function_name = service_function_name
        self._location = location

    @classmethod
    def from_dict(cls, dikt) -> 'LocationPaasDeploy':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The location_paas_deploy of this LocationPaasDeploy.  # noqa: E501
        :rtype: LocationPaasDeploy
        """
        return util.deserialize_model(dikt, cls)

    @property
    def service_function_name(self) -> str:
        """Gets the service_function_name of this LocationPaasDeploy.


        :return: The service_function_name of this LocationPaasDeploy.
        :rtype: str
        """
        return self._service_function_name

    @service_function_name.setter
    def service_function_name(self, service_function_name: str):
        """Sets the service_function_name of this LocationPaasDeploy.


        :param service_function_name: The service_function_name of this LocationPaasDeploy.
        :type service_function_name: str
        """

        self._service_function_name = service_function_name

    @property
    def location(self) -> str:
        """Gets the location of this LocationPaasDeploy.


        :return: The location of this LocationPaasDeploy.
        :rtype: str
        """
        return self._location

    @location.setter
    def location(self, location: str):
        """Sets the location of this LocationPaasDeploy.


        :param location: The location of this LocationPaasDeploy.
        :type location: str
        """

        self._location = location
