# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RemoveNode(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, hostname: str=None, ip: str=None, password: str=None):  # noqa: E501
        """RemoveNode - a model defined in Swagger

        :param name: The name of this RemoveNode.  # noqa: E501
        :type name: str
        :param hostname: The hostname of this RemoveNode.  # noqa: E501
        :type hostname: str
        :param ip: The ip of this RemoveNode.  # noqa: E501
        :type ip: str
        :param password: The password of this RemoveNode.  # noqa: E501
        :type password: str
        """
        self.swagger_types = {
            'name': str,
            'hostname': str,
            'ip': str,
            'password': str
        }

        self.attribute_map = {
            'name': 'name',
            'hostname': 'hostname',
            'ip': 'ip',
            'password': 'password'
        }
        self._name = name
        self._hostname = hostname
        self._ip = ip
        self._password = password

    @classmethod
    def from_dict(cls, dikt) -> 'RemoveNode':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The removeNode of this RemoveNode.  # noqa: E501
        :rtype: RemoveNode
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this RemoveNode.


        :return: The name of this RemoveNode.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this RemoveNode.


        :param name: The name of this RemoveNode.
        :type name: str
        """

        self._name = name

    @property
    def hostname(self) -> str:
        """Gets the hostname of this RemoveNode.


        :return: The hostname of this RemoveNode.
        :rtype: str
        """
        return self._hostname

    @hostname.setter
    def hostname(self, hostname: str):
        """Sets the hostname of this RemoveNode.


        :param hostname: The hostname of this RemoveNode.
        :type hostname: str
        """

        self._hostname = hostname

    @property
    def ip(self) -> str:
        """Gets the ip of this RemoveNode.


        :return: The ip of this RemoveNode.
        :rtype: str
        """
        return self._ip

    @ip.setter
    def ip(self, ip: str):
        """Sets the ip of this RemoveNode.


        :param ip: The ip of this RemoveNode.
        :type ip: str
        """

        self._ip = ip

    @property
    def password(self) -> str:
        """Gets the password of this RemoveNode.


        :return: The password of this RemoveNode.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this RemoveNode.


        :param password: The password of this RemoveNode.
        :type password: str
        """

        self._password = password
