# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ServiceFunctionIndex(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, service_function_name: str=None, service_function_index: int=None):  # noqa: E501
        """ServiceFunctionIndex - a model defined in Swagger

        :param service_function_name: The service_function_name of this ServiceFunctionIndex.  # noqa: E501
        :type service_function_name: str
        :param service_function_index: The service_function_index of this ServiceFunctionIndex.  # noqa: E501
        :type service_function_index: int
        """
        self.swagger_types = {
            'service_function_name': str,
            'service_function_index': int
        }

        self.attribute_map = {
            'service_function_name': 'service_function_name',
            'service_function_index': 'service_function_index'
        }
        self._service_function_name = service_function_name
        self._service_function_index = service_function_index

    @classmethod
    def from_dict(cls, dikt) -> 'ServiceFunctionIndex':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The serviceFunctionIndex of this ServiceFunctionIndex.  # noqa: E501
        :rtype: ServiceFunctionIndex
        """
        return util.deserialize_model(dikt, cls)

    @property
    def service_function_name(self) -> str:
        """Gets the service_function_name of this ServiceFunctionIndex.


        :return: The service_function_name of this ServiceFunctionIndex.
        :rtype: str
        """
        return self._service_function_name

    @service_function_name.setter
    def service_function_name(self, service_function_name: str):
        """Sets the service_function_name of this ServiceFunctionIndex.


        :param service_function_name: The service_function_name of this ServiceFunctionIndex.
        :type service_function_name: str
        """

        self._service_function_name = service_function_name

    @property
    def service_function_index(self) -> int:
        """Gets the service_function_index of this ServiceFunctionIndex.


        :return: The service_function_index of this ServiceFunctionIndex.
        :rtype: int
        """
        return self._service_function_index

    @service_function_index.setter
    def service_function_index(self, service_function_index: int):
        """Sets the service_function_index of this ServiceFunctionIndex.


        :param service_function_index: The service_function_index of this ServiceFunctionIndex.
        :type service_function_index: int
        """

        self._service_function_index = service_function_index
