apiVersion: apps/v1
kind: Deployment
metadata:
  name: workfloweditor
spec:
  selector:
    matchLabels:
      app: workfloweditor
  replicas: 1
  template:
    metadata:
      labels:
        app: workfloweditor
        access-ml-pipeline: "true"
    spec:
      containers:
      - name: workfloweditor
        image: gsamaras/workflow-editor:workfloweditortag10
        imagePullPolicy: Always
        ports:
        - name: app
          containerPort: 5000
          protocol: TCP
      nodeSelector:
        location: Peania_Athens_19002