apiVersion: apps/v1
kind: Deployment
metadata:
  name: workfloweditor
spec:
  selector:
    matchLabels:
      app: workfloweditor
  replicas: 1
  template:
    metadata:
      labels:
        app: workfloweditor
        access-ml-pipeline: "true"
    spec:
      containers:
      - name: workfloweditor
        image: karaeorge/workflow-editor:0
        imagePullPolicy: Always
        ports:
        - name: app
          containerPort: 5000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: workfloweditor-service
  labels:
    app: workfloweditor
  annotations:
    # service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    # service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    # service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
spec:
  type: ClusterIP
  ports:
  - port: 5000
  selector:
    app: workfloweditor