---
- hosts: localhost
  become: false

  vars:
    from_dir: /home/vibm/kubernetes/
    to_dir: "{{ playbook_dir }}/Infrastructure/"

    NVIDIA_code_from_dir: /home/vibm/NVIDIA/examples/nvidia-gpu/
    NVIDIA_code_to_dir: "{{ playbook_dir }}/NVIDIA/GPU/yolo-detectron/"
    
  tasks:
  - name: Select files from folder using wildcards
    find:
      patterns: "*.sh,*.yaml,*.json,Vagrantfile"
      paths:
       - "{{ from_dir }}"
    register: files_to_copy
  - name: Check the structure and content of the variable
    debug:
      var: files_to_copy
  - name: Print a debug message
    debug:
      msg: "{{ item.value|json_query('[].path') }}" # | selectattr('examined' ) }}"
    loop: "{{ files_to_copy | dict2items | list }}"
  - name: Copy files from source-folder --> "kubernetes" to dest-folder --> "icom-hub" 
    copy:
      src="{{ item.path }}"
      dest="{{ to_dir }}"
      mode=0777
    with_items: "{{ files_to_copy.files }}"
  - name: Copy Folders FROM kubernetes INTO icom-hub
    ansible.builtin.copy:
      src: "{{ from_dir }}/kubernetes-setup"
      dest: "{{ to_dir }}"
  - name: Find backup files with tilde(~) at the end of filename
    ansible.builtin.find:
      patterns: "*.*~"
      paths: "{{ to_dir }}/kubernetes-setup/"
      recurse: yes
    register: files_with_tilde
  - debug:
      var: files_with_tilde
  - name: Remove(delete) files with tilde at the end of filename
    ansible.builtin.file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ files_with_tilde.files }}"
  - name: Copy files that use NVIDIA GPU for Machine Learning tasks
    ansible.builtin.copy:
      src: "{{ NVIDIA_code_from_dir }}"
      dest: "{{ NVIDIA_code_to_dir }}"
  - name: Delete backup files with tilde at the end of filename
    ansible.builtin.find:
      patterns: "#*#,*~,*.run"
      paths: "{{ NVIDIA_code_to_dir }}"
      recurse: yes
    register: nvidia_code_with_tilde
  - name: Files with tilde at the end in NVIDIA-CODE
    ansible.builtin.debug:
      var: nvidia_code_with_tilde.files | json_query('[].path')
  - name: Remove Backup Files from NVIDIA-GPU Code
    ansible.builtin.file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ nvidia_code_with_tilde.files }}"
  - name: Create .GITIGNORE for large RUN files - Otherwise Upload is Rejected
    ansible.builtin.copy:
      dest: "{{  NVIDIA_code_to_dir }}/.gitignore"
      content: | 
        *.run
        
        

   
       
