---
apiVersion: v1
kind: Service
metadata:
  name: consul-ui
  namespace: tandem
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8500
    nodePort: 31960
  selector:
    app.kubernetes.io/name: consul
  sessionAffinity: None
  type: NodePort
---
