---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: prometheus-pv
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/home/vagrant/prometheus-store"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus
  name: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: bitnami/prometheus:2.37
        imagePullPolicy: IfNotPresent
        env:
        - name: REDIS_PORT_NUMBER
          value: '7000'
        - name: ALLOW_EMPTY_PASSWORD
          value: 'yes'
        ports:
        - containerPort: 9090
          name: "tcp-redis"
          protocol: TCP
          hostPort: 9090
        # readinessProbe:
        #   failureThreshold: 3
        #   httpGet:
        #     path: /robots.txt
        #     port: 3000
        #     scheme: HTTP
        #   initialDelaySeconds: 30
        #   periodSeconds: 30
        #   successThreshold: 1
        #   timeoutSeconds: 2
        # livenessProbe:
        #   failureThreshold: 3
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        #   successThreshold: 1
        #   tcpSocket:
        #      port: 3000
        #   timeoutSeconds: 1
        resources:
          requests:
            cpu: 250m
            memory: 750Mi
        volumeMounts:
        - mountPath: /etc/prometheus
          name: prometheus-pv
      securityContext:
        fsGroup: 472
        supplementalGroups:
        - 0
      volumes:
      - name: prometheus-pv
        persistentVolumeClaim:
          claimName: prometheus-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  #namespace: tandem
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
    nodePort: 30330
  selector:
    app: prometheus
  sessionAffinity: None
  type: NodePort
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: prometheus-k8s
#spec:
#  ports:
#  - port: 9090
#    protocol: TCP
#    targetPort: 9090
#    nodePort: 31972
#  selector:
#    app.kubernetes.io/name: prometheus
#  sessionAffinity: None
#  type: NodePort
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: grafana-k8s
#spec:
#  ports:
#  - port: 3000
#    protocol: TCP
#    targetPort: 3000
#    nodePort: 31974
#  selector:
#    app.kubernetes.io/name: grafana
#  sessionAffinity: None
#  type: NodePort
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: alertmanager-k8s
#spec:
#  ports:
#  - port: 9093
#    protocol: TCP
#    targetPort: 9093
#    nodePort: 31976
#  selector:
#    app.kubernetes.io/name: alertmanager
#  sessionAffinity: None
#  type: NodePort
#---

  
