---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: rabbitmq-pv
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/home/vagrant/rabbitmq-store"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq-depl
spec:
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.10
        imagePullPolicy: IfNotPresent
        env:
        - name: default_user
          value: 'guest'
        - name: default_password
          value: 'guest'
        ports:
        - containerPort: 5672
          name: "tcp-rabbitmq"
          protocol: TCP
          hostPort: 5672
        # readinessProbe:
        #   failureThreshold: 3
        #   httpGet:
        #     path: /robots.txt
        #     port: 3000
        #     scheme: HTTP
        #   initialDelaySeconds: 30
        #   periodSeconds: 30
        #   successThreshold: 1
        #   timeoutSeconds: 2
        # livenessProbe:
        #   failureThreshold: 3
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        #   successThreshold: 1
        #   tcpSocket:
        #      port: 3000
        #   timeoutSeconds: 1
        resources:
          requests:
            cpu: 250m
            memory: 750Mi
        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq-pv
      securityContext:
        fsGroup: 472
        supplementalGroups:
        - 0
      volumes:
      - name: rabbitmq-pv
        persistentVolumeClaim:
          claimName: rabbitmq-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-http-stats
  namespace: tandem
spec:
  ports:
  - port: 5672
    protocol: TCP
    targetPort: 5672
    nodePort: 31960
  selector:
    app.kubernetes.io/name: rabbitmq
  sessionAffinity: None
  type: NodePort
---
