{
 "title": "Infrastructure Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "TANDEM Node 1 Memory Consumption",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "Utilizatiion" }
   ],
   "targets": [
    {
     "expr": "node_memory_Active_bytes{instance=\"k8smaster\"}/node_memory_MemTotal_bytes{instance=\"k8smaster\"}*100",
     "legendFormat": "TANDEM Node 1 Memory Consumption  - Total Memory : 32 GB"
    }
   ]
  },
  {
   "title": "TANDEM Node 1 CPU Consumption",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "Utilization" }
   ],
   "targets": [
    {
     "expr": "100-avg(rate(node_cpu_seconds_total{instance=\"k8smaster\",mode=\"idle\"}[5m]))*100",
     "legendFormat": "TANDEM Node 1 CPU Consumption - Total CPU vCores :  12"
    }
   ]
  },
  {
   "title": "TANDEM Node 2 Memory Consumption",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent", "label": "Utilization" }
   ],
   "targets": [
    {
     "expr": "node_memory_Active_bytes{instance=\"k8ssecondary\"}/node_memory_MemTotal_bytes{instance=\"k8ssecondary\"}*100",
     "legendFormat": "TANDEM Node 2 Memory Consumption - Total Memory : 16 GB"
    }
   ]
  },
  {
   "title": "TANDEM Node 2 CPU  Consumption",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percent", "label": "Utilization" }
   ],
   "targets": [
    {
     "expr": "100-avg(rate(node_cpu_seconds_total{instance=\"k8ssecondary\",mode=\"idle\"}[5m]))*100",
     "legendFormat": "TANDEM Node 2 CPU  Consumption - Total CPU vCores : 12"
    }
   ]
  }
 ]
}