{
 "title": "Infrastructure Metrics Node 1",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Node 1 Memory Consumption",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "Utilizatiion" }
   ],
   "targets": [
    {
     "expr": "node_memory_Active_bytes{instance=\"compute1\"}/node_memory_MemTotal_bytes{instance=\"compute1\"}*100",
     "legendFormat": "Node 1 Memory Consumption"
    }
   ]
  },
  {
   "title": " Node 1 CPU Consumption",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "Utilization" }
   ],
   "targets": [
    {
     "expr": "100-avg(rate(node_cpu_seconds_total{instance=\"compute1\",mode=\"idle\"}[5m]))*100",
     "legendFormat": "Node 1 CPU Consumption"
    }
   ]
  },
  {
   "title": " Node 1 Transmitted Throughput",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none", "label": "Mbps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{instance=\"compute1\"}[1m]))/1000000*8",
     "legendFormat": "Node 1 Transmitted Throughput"
    }
   ]
  },
  {
   "title": " Node 1 Received Throughput",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "none", "label": "Mbps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{instance=\"compute1\"}[1m]))/1000000*8",
     "legendFormat": "Node 1 Received Throughput"
    }
   ]
  }
 ]
}