{
 "title": "Infrastructure Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Node NODE_NUMBER Memory Consumption",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "Utilizatiion" }
   ],
   "targets": [
    {
     "expr": "node_memory_Active_bytes{instance=\"NODE_NAME\"}/node_memory_MemTotal_bytes{instance=\"NODE_NAME\"}*100",
     "legendFormat": "Node NODE_NUMBER Memory Consumption"
    }
   ]
  },
  {
   "title": " Node 1 CPU Consumption",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "Utilization" }
   ],
   "targets": [
    {
     "expr": "100-avg(rate(node_cpu_seconds_total{instance=\"NODE_NAME\",mode=\"idle\"}[5m]))*100",
     "legendFormat": "Node NODE_NUMBER CPU Consumption"
    }
   ]
  },
  {
   "title": "Node NODE_NUMBER Transmitted Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{instance=\"NODE_NAME\"}[1m]))/1000000*8",
     "legendFormat": "Node NODE_NUMBER Transmitted Throughput"
    }
   ]
  },
  {
   "title": "Node NODE_NUMBER Received Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{instance=\"NODE_NAME\"}[1m]))/1000000*8",
     "legendFormat": "Node NODE_NUMBER Received Throughput"
    }
   ]
  }
 ]
}