{
 "title": "PaaS Edgex Services",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Edgex-Core-Data",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "yaxes": [
    { "format": "decmbytes", "label": "Memory Usage" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"pi-edge\",container=\"edgex-core-data\"}/1000000",
     "legendFormat": "Edgex-Core-Data Memory Consumption "
    }
   ]
  },
  {
   "title": "Edgex-Core-Data",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "CPU Utilization" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"pi-edge\",container=\"edgex-core-data\"}[5m]))/sum(20000/container_spec_cpu_period{namespace=\"pi-edge\",container=\"edgex-core-data\"})*100",
     "legendFormat": "Edgex-Core-Data CPU Consumption - Max  Limit CPU vCores: 0.5"
    }
   ]
  },
  {
   "title": "Edgex-Core-Command",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "decmbytes", "label": "Memory Usage" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"pi-edge\",container=\"edgex-core-command\"}/1000000",
     "legendFormat": "Edgex-Core-Command Memory Consumption"
    }
   ]
  },
  {
   "title": "Edgex-Core-Command",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "percent", "label": "CPU Utilization" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"pi-edge\",container=\"edgex-core-command\"}[5m]))/sum(20000/container_spec_cpu_period{namespace=\"pi-edge\",container=\"edgex-core-command\"})*100",
     "legendFormat": "Edgex-Core-Command CPU Consumption - Max Limit CPU vCores: 0.5"
    }
   ]
  },
  {
   "title": "Edgex-Kuiper",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decmbytes", "label": "Memory Usage" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"pi-edge\",container=\"edgex-kuiper\"}/1000000",
     "legendFormat": "Edgex-Kuiper Memory Consumption"
    }
   ]
  },
  {
   "title": "Edgex-Kuiper",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "percent", "label": "CPU Utilization" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"pi-edge\",container=\"edgex-kuiper\"}[5m]))/sum(20000/container_spec_cpu_period{namespace=\"pi-edge\",container=\"edgex-kuiper\"})*100",
     "legendFormat": "Edgex-Kuiper CPU Consumption - Max Limit CPU vCores: 0.5"
    }
   ]
  },
  {
   "title": "Edgex-Redis",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "decmbytes", "label": "Memory Usage" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"pi-edge\",container=\"edgex-redis\"}/1000000",
     "legendFormat": "Edgex-Redis Memory Consumption"
    }
   ]
  },
  {
   "title": "Edgex-Redis",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "percent", "label": "CPU Utilization" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"pi-edge\",container=\"edgex-redis\"}[5m]))/sum(20000/container_spec_cpu_period{namespace=\"pi-edge\",container=\"edgex-redis\"})*100",
     "legendFormat": "Edgex-Redis CPU Consumption - Max Limit CPU vCores: 0.5"
    }
   ]
  }
 ]
}