{
 "title": "PaaS  IoT Monitoring & Analytics  Services",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Mqtt",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decmbytes", "label": "Memory Usage" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"pi-edge\",container=\"iotmonitoring-mqtt\"}/1000000",
     "legendFormat": "Mqtt Memory Consumption"
    }
   ]
  },
  {
   "title": "Mqtt",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "CPU Utilization" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"pi-edge\",container=\"iotmonitoring-mqtt\"}[5m]))/sum(20000/container_spec_cpu_period{namespace=\"pi-edge\",container=\"iotmonitoring-mqtt\"})*100",
     "legendFormat": "Mqtt CPU Consumption - Max Limit CPU vCores : 0.5"
    }
   ]
  },
  {
   "title": "InfluxDB",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "decmbytes", "label": "Memory Usage " }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"pi-edge\",container=\"iotmonitoring-influxdb\"}/1000000",
     "legendFormat": "InfuxDB Memory Consumption"
    }
   ]
  },
  {
   "title": "InfluxDB",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "CPU Utilization" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"pi-edge\",container=\"iotmonitoring-influxdb\"}[5m]))/sum(20000/container_spec_cpu_period{namespace=\"pi-edge\",container=\"iotmonitoring-influxdb\"})*100",
     "legendFormat": "InfluxDB CPU Consumption - Max Limit CPU vCores : 0.5"
    }
   ]
  },
  {
   "title": "Temp. & Humidity App",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"pi-edge\",container=\"iotmonitoring-messenger\"}/1000000",
     "legendFormat": "Temp. & Humidity App Memory Consumption"
    }
   ]
  },
  {
   "title": "Temp. & Humidity App",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "percent", "label": "CPU Utilization" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"pi-edge\",container=\"iotmonitoring-messenger\"}[5m]))/sum(20000/container_spec_cpu_period{namespace=\"pi-edge\",container=\"iotmonitoring-messenger\"})*100",
     "legendFormat": "Temp. & Humidity App CPU Consumption - Max Limit CPU vCores : 0.5"
    }
   ]
  },
  {
   "title": "Grafana",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "decmbytes", "label": "Memory Usage " }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"pi-edge\",container=\"iotmonitoring-grafana\"}/1000000",
     "legendFormat": "Grafana Memory Consumption"
    }
   ]
  },
  {
   "title": "Grafana ",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "percent", "label": "CPU Utilization" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"pi-edge\",container=\"iotmonitoring-grafana\"}[5m]))/sum(container_spec_cpu_quota{namespace=\"pi-edge\",container=\"iotmonitoring-grafana\"}/container_spec_cpu_period{namespace=\"pi-edge\",container=\"iotmonitoring-grafana\"})*100",
     "legendFormat": "Grafana CPU Consumption - Max Limit CPU vCores : 0.5"
    }
   ]
  }
 ]
}