{
 "title": "Service Functions pi-edge",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "SERVICE_FUNCTION_INSTANCE_NAME Memory Consumption",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decmbytes", "label": "Memory Usage" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"pi-edge\",container=\"SERVICE_FUNCTION_INSTANCE_NAME\"}/1000000)/count(container_memory_usage_bytes{namespace=\"pi-edge\",container=\"SERVICE_FUNCTION_INSTANCE_NAME\"})",
     "legendFormat": "Memory Consumption"
    }
   ]
  },
  {
   "title": "SERVICE_FUNCTION_INSTANCE_NAME Received Throughput",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Mbps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total,{namespace=\"pi-edge\", pod=~\"SERVICE_FUNCTION_INSTANCE_NAME.*\"}[1m]))/1000000*8",
     "legendFormat": "Received Throughput"
    }
   ]
  },
  {
   "title": "SERVICE_FUNCTION_INSTANCE_NAME Transmitted Throughput",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Mbps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total,{namespace=\"pi-edge\", pod=~\"SERVICE_FUNCTION_INSTANCE_NAME.*\"}[1m]))/1000000*8",
     "legendFormat": "Transmitted Throughput"
    }
   ]
  },
  {
   "title": "SERVICE_FUNCTION_INSTANCE_NAME CPU Consumption",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "CPU Utilization" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"pi-edge\",container=\"SERVICE_FUNCTION_INSTANCE_NAME\"}[5m]))/sum(container_spec_cpu_quota{namespace=\"pi-edge\",container=\"SERVICE_FUNCTION_INSTANCE_NAME\"}/container_spec_cpu_period{namespace=\"pi-edge\",container=\"SERVICE_FUNCTION_INSTANCE_NAME\"})*100",
     "legendFormat": "CPU Consumption"
    }
   ]
  }
 ]
}