{
 "title": "TANDEM Node 2 Services",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Grafana",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "yaxes": [
    { "format": "decmbytes", "label": "Memory Usage" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"pi-edge\",node=\"k8ssecondary\",container=\"iotmonitoring-grafana\"}/1000000",
     "legendFormat": "Grafana Memory Consumption "
    }
   ]
  },
  {
   "title": "Grafana",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "CPU Utilization" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"pi-edge\",node=\"k8ssecondary\",container=\"iotmonitoring-grafana\"}[5m]))/sum(20000/container_spec_cpu_period{namespace=\"pi-edge\",node=\"k8ssecondary\",container=\"iotmonitoring-grafana\"})*100",
     "legendFormat": "Grafana CPU Consumption - Max Limit CPU vCores : 0.5"
    }
   ]
  },
  {
   "title": "Temp. & Humidity App",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "yaxes": [
    { "format": "decmbytes", "label": "Memory Usage" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"pi-edge\",node=\"k8ssecondary\",container=\"iotmonitoring-messenger\"}/1000000",
     "legendFormat": "Temp. & Humidity App Memory Consumption "
    }
   ]
  },
  {
   "title": "Temp. & Humidity App",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percent", "label": "CPU Utilization" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"pi-edge\",node=\"k8ssecondary\",container=\"iotmonitoring-messenger\"}[5m]))/sum(20000/container_spec_cpu_period{namespace=\"pi-edge\",node=\"k8ssecondary\",container=\"iotmonitoring-messenger\"})*100",
     "legendFormat": "Temp. & Humidity App CPU Consumption - Max Limit CPU vCores : 0.5"
    }
   ]
  },
  {
   "title": "Mqtt",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "yaxes": [
    { "format": "decmbytes", "label": "Memory Usage" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"pi-edge\",node=\"k8ssecondary\",container=\"iotmonitoring-mqtt\"}/1000000",
     "legendFormat": "Mqtt Memory Consumption "
    }
   ]
  },
  {
   "title": "Mqtt",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "percent", "label": "CPU Utilization" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"pi-edge\",node=\"k8ssecondary\",container=\"iotmonitoring-mqtt\"}[5m]))/sum(20000/container_spec_cpu_period{namespace=\"pi-edge\",node=\"k8ssecondary\",container=\"iotmonitoring-mqtt\"})*100",
     "legendFormat": "Mqtt CPU Consumption - Max Limit CPU vCores : 0.5"
    }
   ]
  },
  {
   "title": "Influxdb",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "yaxes": [
    { "format": "decmbytes", "label": "Memory Usage" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"pi-edge\",node=\"k8ssecondary\",container=\"iotmonitoring-influxdb\"}/1000000",
     "legendFormat": "Influxdb Memory Consumption "
    }
   ]
  },
  {
   "title": "InfluxDB",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "percent", "label": "CPU Utilization" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"pi-edge\",node=\"k8ssecondary\",container=\"iotmonitoring-influxdb\"}[5m]))/sum(20000/container_spec_cpu_period{namespace=\"pi-edge\",node=\"k8ssecondary\",container=\"iotmonitoring-influxdb\"})*100",
     "legendFormat": "InfluxDB CPU Consumption - Max Limit CPU vCores : 0.5"
    }
   ]
  },
  {
   "title": "Edgex-Kuiper",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "decmbytes", "label": "Memory Usage" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"pi-edge\",node=\"k8ssecondary\",container=\"edgex-kuiper\"}/1000000",
     "legendFormat": "Edgex-Kuiper Memory Consumption"
    }
   ]
  },
  {
   "title": "Edgex-Kuiper",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "percent", "label": "Utilization" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"pi-edge\",node=\"k8ssecondary\",container=\"edgex-kuiper\"}[5m]))/sum(20000/container_spec_cpu_period{namespace=\"pi-edge\",node=\"k8ssecondary\",container=\"edgex-kuiper\"})*100",
     "legendFormat": "Edgex-Kuiper CPU Consumption - Max Limit CPU vCores: 0.5"
    }
   ]
  },
  {
   "title": "Edgex-Redis",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "decmbytes", "label": "Memory Usage" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"pi-edge\",node=\"k8ssecondary\",container=\"edgex-redis\"}/1000000",
     "legendFormat": "Edgex-Redis Memory Consumption"
    }
   ]
  },
  {
   "title": "Edgex-Redis",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "percent", "label": "Utilization" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"pi-edge\",node=\"k8ssecondary\",container=\"edgex-redis\"}[5m]))/sum(20000/container_spec_cpu_period{namespace=\"pi-edge\",node=\"k8ssecondary\",container=\"edgex-redis\"})*100",
     "legendFormat": "Edgex-Redis CPU Consumption - Max Limit CPU vCores: 0.5"
    }
   ]
  },
  {
   "title": "Edgex-Core-Command",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "decmbytes", "label": "Memory Usage" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"pi-edge\",node=\"k8ssecondary\",container=\"edgex-core-command\"}/1000000",
     "legendFormat": "Edgex-Core-Command Memory Consumption"
    }
   ]
  },
  {
   "title": "Edgex-Core-Command",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "percent", "label": "Utilization" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"pi-edge\",node=\"k8ssecondary\",container=\"edgex-core-command\"}[5m]))/sum(20000/container_spec_cpu_period{namespace=\"pi-edge\",node=\"k8ssecondary\",container=\"edgex-core-command\"})*100",
     "legendFormat": "Edgex-Core-Command CPU Consumption - Max Limit CPU vCores: 0.5"
    }
   ]
  },
  {
   "title": "Edgex-Core-Data",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "yaxes": [
    { "format": "decmbytes", "label": "Memory Usage" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"pi-edge\",node=\"k8ssecondary\",container=\"edgex-core-data\"}/1000000",
     "legendFormat": "Edgex-Core-Data Memory Consumption "
    }
   ]
  },
  {
   "title": "Edgex-Core-Data",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "percent", "label": "Utilization" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"pi-edge\",node=\"k8ssecondary\",container=\"edgex-core-data\"}[5m]))/sum(20000/container_spec_cpu_period{namespace=\"pi-edge\",node=\"k8ssecondary\",container=\"edgex-core-data\"})*100",
     "legendFormat": "Edgex-Core-Data CPU Consumption - Max  Limit CPU vCores: 0.5"
    }
   ]
  }
 ]
}