apiVersion: v1
kind: Service
metadata:
  labels:
    app: private-repository-k8s
  name: private-repository-k8s
spec:
  ports:
    - port: 5050
      nodePort: 31320
      protocol: TCP
      targetPort: registry-pod-port
  selector:
    app: private-repository-k8s
  type: NodePort