# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class EopDConfigurability(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, foo: str=None):  # noqa: E501
        """EopDConfigurability - a model defined in Swagger

        :param foo: The foo of this EopDConfigurability.  # noqa: E501
        :type foo: str
        """
        self.swagger_types = {
            'foo': str
        }

        self.attribute_map = {
            'foo': 'foo'
        }
        self._foo = foo

    @classmethod
    def from_dict(cls, dikt) -> 'EopDConfigurability':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The eopD_configurability of this EopDConfigurability.  # noqa: E501
        :rtype: EopDConfigurability
        """
        return util.deserialize_model(dikt, cls)

    @property
    def foo(self) -> str:
        """Gets the foo of this EopDConfigurability.


        :return: The foo of this EopDConfigurability.
        :rtype: str
        """
        return self._foo

    @foo.setter
    def foo(self, foo: str):
        """Sets the foo of this EopDConfigurability.


        :param foo: The foo of this EopDConfigurability.
        :type foo: str
        """

        self._foo = foo
