# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class EopDKpis(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, availability: str=None, latency: str=None):  # noqa: E501
        """EopDKpis - a model defined in Swagger

        :param availability: The availability of this EopDKpis.  # noqa: E501
        :type availability: str
        :param latency: The latency of this EopDKpis.  # noqa: E501
        :type latency: str
        """
        self.swagger_types = {
            'availability': str,
            'latency': str
        }

        self.attribute_map = {
            'availability': 'availability',
            'latency': 'latency'
        }
        self._availability = availability
        self._latency = latency

    @classmethod
    def from_dict(cls, dikt) -> 'EopDKpis':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The eopD_kpis of this EopDKpis.  # noqa: E501
        :rtype: EopDKpis
        """
        return util.deserialize_model(dikt, cls)

    @property
    def availability(self) -> str:
        """Gets the availability of this EopDKpis.


        :return: The availability of this EopDKpis.
        :rtype: str
        """
        return self._availability

    @availability.setter
    def availability(self, availability: str):
        """Sets the availability of this EopDKpis.


        :param availability: The availability of this EopDKpis.
        :type availability: str
        """

        self._availability = availability

    @property
    def latency(self) -> str:
        """Gets the latency of this EopDKpis.


        :return: The latency of this EopDKpis.
        :rtype: str
        """
        return self._latency

    @latency.setter
    def latency(self, latency: str):
        """Sets the latency of this EopDKpis.


        :param latency: The latency of this EopDKpis.
        :type latency: str
        """

        self._latency = latency
