# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class K8sRegistrationRequestEopAuthCredentials(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, username: str=None, password: str=None, token: str=None):  # noqa: E501
        """K8sRegistrationRequestEopAuthCredentials - a model defined in Swagger

        :param username: The username of this K8sRegistrationRequestEopAuthCredentials.  # noqa: E501
        :type username: str
        :param password: The password of this K8sRegistrationRequestEopAuthCredentials.  # noqa: E501
        :type password: str
        :param token: The token of this K8sRegistrationRequestEopAuthCredentials.  # noqa: E501
        :type token: str
        """
        self.swagger_types = {
            'username': str,
            'password': str,
            'token': str
        }

        self.attribute_map = {
            'username': 'username',
            'password': 'password',
            'token': 'token'
        }
        self._username = username
        self._password = password
        self._token = token

    @classmethod
    def from_dict(cls, dikt) -> 'K8sRegistrationRequestEopAuthCredentials':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The k8sRegistrationRequest_eopAuthCredentials of this K8sRegistrationRequestEopAuthCredentials.  # noqa: E501
        :rtype: K8sRegistrationRequestEopAuthCredentials
        """
        return util.deserialize_model(dikt, cls)

    @property
    def username(self) -> str:
        """Gets the username of this K8sRegistrationRequestEopAuthCredentials.


        :return: The username of this K8sRegistrationRequestEopAuthCredentials.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this K8sRegistrationRequestEopAuthCredentials.


        :param username: The username of this K8sRegistrationRequestEopAuthCredentials.
        :type username: str
        """

        self._username = username

    @property
    def password(self) -> str:
        """Gets the password of this K8sRegistrationRequestEopAuthCredentials.


        :return: The password of this K8sRegistrationRequestEopAuthCredentials.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this K8sRegistrationRequestEopAuthCredentials.


        :param password: The password of this K8sRegistrationRequestEopAuthCredentials.
        :type password: str
        """

        self._password = password

    @property
    def token(self) -> str:
        """Gets the token of this K8sRegistrationRequestEopAuthCredentials.


        :return: The token of this K8sRegistrationRequestEopAuthCredentials.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token: str):
        """Sets the token of this K8sRegistrationRequestEopAuthCredentials.


        :param token: The token of this K8sRegistrationRequestEopAuthCredentials.
        :type token: str
        """

        self._token = token
