# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PaasRegistrationRequestAutoscalingPolicies(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, metric: str=None, limit: str=None, request: str=None, util_percent: float=None):  # noqa: E501
        """PaasRegistrationRequestAutoscalingPolicies - a model defined in Swagger

        :param metric: The metric of this PaasRegistrationRequestAutoscalingPolicies.  # noqa: E501
        :type metric: str
        :param limit: The limit of this PaasRegistrationRequestAutoscalingPolicies.  # noqa: E501
        :type limit: str
        :param request: The request of this PaasRegistrationRequestAutoscalingPolicies.  # noqa: E501
        :type request: str
        :param util_percent: The util_percent of this PaasRegistrationRequestAutoscalingPolicies.  # noqa: E501
        :type util_percent: float
        """
        self.swagger_types = {
            'metric': str,
            'limit': str,
            'request': str,
            'util_percent': float
        }

        self.attribute_map = {
            'metric': 'metric',
            'limit': 'limit',
            'request': 'request',
            'util_percent': 'util_percent'
        }
        self._metric = metric
        self._limit = limit
        self._request = request
        self._util_percent = util_percent

    @classmethod
    def from_dict(cls, dikt) -> 'PaasRegistrationRequestAutoscalingPolicies':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PaasRegistrationRequest_autoscaling_policies of this PaasRegistrationRequestAutoscalingPolicies.  # noqa: E501
        :rtype: PaasRegistrationRequestAutoscalingPolicies
        """
        return util.deserialize_model(dikt, cls)

    @property
    def metric(self) -> str:
        """Gets the metric of this PaasRegistrationRequestAutoscalingPolicies.


        :return: The metric of this PaasRegistrationRequestAutoscalingPolicies.
        :rtype: str
        """
        return self._metric

    @metric.setter
    def metric(self, metric: str):
        """Sets the metric of this PaasRegistrationRequestAutoscalingPolicies.


        :param metric: The metric of this PaasRegistrationRequestAutoscalingPolicies.
        :type metric: str
        """

        self._metric = metric

    @property
    def limit(self) -> str:
        """Gets the limit of this PaasRegistrationRequestAutoscalingPolicies.


        :return: The limit of this PaasRegistrationRequestAutoscalingPolicies.
        :rtype: str
        """
        return self._limit

    @limit.setter
    def limit(self, limit: str):
        """Sets the limit of this PaasRegistrationRequestAutoscalingPolicies.


        :param limit: The limit of this PaasRegistrationRequestAutoscalingPolicies.
        :type limit: str
        """

        self._limit = limit

    @property
    def request(self) -> str:
        """Gets the request of this PaasRegistrationRequestAutoscalingPolicies.


        :return: The request of this PaasRegistrationRequestAutoscalingPolicies.
        :rtype: str
        """
        return self._request

    @request.setter
    def request(self, request: str):
        """Sets the request of this PaasRegistrationRequestAutoscalingPolicies.


        :param request: The request of this PaasRegistrationRequestAutoscalingPolicies.
        :type request: str
        """

        self._request = request

    @property
    def util_percent(self) -> float:
        """Gets the util_percent of this PaasRegistrationRequestAutoscalingPolicies.


        :return: The util_percent of this PaasRegistrationRequestAutoscalingPolicies.
        :rtype: float
        """
        return self._util_percent

    @util_percent.setter
    def util_percent(self, util_percent: float):
        """Sets the util_percent of this PaasRegistrationRequestAutoscalingPolicies.


        :param util_percent: The util_percent of this PaasRegistrationRequestAutoscalingPolicies.
        :type util_percent: float
        """

        self._util_percent = util_percent
