# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PaasDeregistrationRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, paas_service_name: str=None):  # noqa: E501
        """PaasDeregistrationRequest - a model defined in Swagger

        :param paas_service_name: The paas_service_name of this PaasDeregistrationRequest.  # noqa: E501
        :type paas_service_name: str
        """
        self.swagger_types = {
            'paas_service_name': str
        }

        self.attribute_map = {
            'paas_service_name': 'paas_service_name'
        }
        self._paas_service_name = paas_service_name

    @classmethod
    def from_dict(cls, dikt) -> 'PaasDeregistrationRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PaasDeregistrationRequest of this PaasDeregistrationRequest.  # noqa: E501
        :rtype: PaasDeregistrationRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def paas_service_name(self) -> str:
        """Gets the paas_service_name of this PaasDeregistrationRequest.


        :return: The paas_service_name of this PaasDeregistrationRequest.
        :rtype: str
        """
        return self._paas_service_name

    @paas_service_name.setter
    def paas_service_name(self, paas_service_name: str):
        """Sets the paas_service_name of this PaasDeregistrationRequest.


        :param paas_service_name: The paas_service_name of this PaasDeregistrationRequest.
        :type paas_service_name: str
        """

        self._paas_service_name = paas_service_name
