FROM nvcr.io/nvidia/pytorch:21.08-py3

RUN apt-get update
RUN apt-get install -y libgl-dev

RUN git clone https://github.com/ultralytics/yolov5.git

WORKDIR yolov5
RUN pip install -r requirements.txt

ADD yolo5-inference-demo.py /workspace/

#ADD zidane.jpg /workspace/
ADD smart-city-001.jpg /workspace/

#CMD python create-classification-model.py