groups:
  arm:
    operating_mode: position
    profile_type: velocity
    profile_velocity: 131
    profile_acceleration: 25
    torque_enable: true

singles:
  gripper: linear_position #current_based_position
    operating_mode: 
    profile_type: velocity
    profile_velocity: 131
    profile_acceleration: 15
    torque_enable: true
