apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: piedgecontroller
  name: piedgecontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: piedgecontroller
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        #io.kompose.network/netEMPkub: "true"
        io.kompose.service: piedgecontroller
    spec:
      containers:
        - env:
            - name: KUBERNETES_MASTER_HOST
              #example value
              value: https://146.124.106.179:16443 
            - name: KUBERNETES_MASTER_TOKEN
               #example value
              value: b3lIOWFQM3NUTWJpSUVBMDNGNmlmVG4wQkd5dXFmWTdFUlFWQVo3UnEycz0K 
            - name: EMP_STORAGE_URI
              #value: mongodb://mongopiedge:27017
              value: mongodb://mongoemp:27017
            - name: MONITORING_IP
              value: "203.0.113.130"
            - name: MONITORING_NODE_PORT
              value: "3000"
            - name: SYSTEM_DATABASE_PASSWORD
              value: "pslicom"
            - name: MONITORING_SERVICE_PASSWORD
              value: "tandem"
          image: nikospsar/pi_edge:3.0.2
          name: piedgecontroller
          ports:
            - containerPort: 8080
          resources: {}
          imagePullPolicy: Always
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: piedgecontroller
  name: piedgecontroller
spec:
  type: NodePort
  ports:
    - name: "8080"
      nodePort: 32415
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: piedgecontroller
status:
  loadBalancer: {}