apiVersion: apps/v1
kind: Deployment
metadata:
  name: predict
  labels:
    app: predict
spec:
  replicas: 1
  selector:
    matchLabels:
      app: predict
  template:
    metadata:
      labels:
        app: predict
    spec:
      containers:
        - env:
            - name: PROMETHEUS_IP
              # For tansecond-cluster: localhost:8080 (old one 30000)
              # For Tandem VM:
              value: "http://localhost:8080"
          name: predict
          image: gsamaras/infrastructure_predict:predict_api
          ports:
            - containerPort: 5556
          imagePullPolicy: Always
