apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: systemmanager
  name: systemmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: systemmanager
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        #io.kompose.network/netEMPkub: "true"
        io.kompose.service: systemmanager
    spec:
      containers:
        - env:
#            - name: KUBERNETES_MASTER_HOST
#              #example value
#              value: https://146.124.106.179:16443 #
#            - name: KUBERNETES_MASTER_TOKEN
#               #example value
#              value: b3lIOWFQM3NUTWJpSUVBMDNGNmlmVG4wQkd5dXFmWTdFUlFWQVo3UnEycz0K
            - name: EMP_STORAGE_URI
              value: mongodb://mongopiedge:27017
          image: marievixezonaki/system-manager:2.2
          name: systemmanager
          ports:
            - containerPort: 8083
          resources: {}
          imagePullPolicy: Always
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: systemmanager
  name: systemmanager
spec:
  type: NodePort
  ports:
    - name: "8083"
      nodePort: 30003
      port: 8083
      targetPort: 8083
  selector:
    io.kompose.service: systemmanager
status:
  loadBalancer: {}
