apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glusterpvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: pv003
