apiVersion: v1
kind: Service
metadata:
  labels:
    app: influxdb
  name: influxdb
  namespace: kostas-tandem
spec:
  ports:
    - name: "8086"
      protocol: TCP
      nodePort: 30886
      port: 8086
      targetPort: 8086
  selector:
    app: influxdb
  type: NodePort
