apiVersion: v1  
kind: PersistentVolumeClaim  
metadata:  
  name: influxdb-data  
  namespace: kostas-tandem
spec:  
  accessModes:  
  - ReadWriteOnce  
  resources:  
    requests:  
      storage: 2Gi
