apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
spec:
  service:
    ports:
      - port: 12001
        targetPort: 12001
  webhook:
    # event-source can run multiple HTTP servers. Simply define a unique port to start a new HTTP server
    notification:
      # port to run HTTP server on
      port: "12001"
      # endpoint to listen to
      endpoint: /notification
      # HTTP request method to allow. In this case, only POST requests are accepted
      method: POST
      
---



apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
  namespace: argo-events
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: notify1-dep
      eventSourceName: webhook
      eventName: notification
  triggers:
    - template:
        conditions: "notify1-dep"
        name: webhook1-workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: webhook-
              spec:
                entrypoint: whalesay
                arguments:
                  parameters:
                  - name: api
                    value:
                  - name: address
                    value:
                  - name: latitude
                    value:
                  - name: longitude
                    value:
                  - name: user_type
                    value:
                  - name: distance
                    value:
                  - name: humidity
                    value:
                  - name: temperature
                    value:
                  - name: datetime
                    value:
                  - name: address_name
                    value:
                templates:
                - name: whalesay
                  inputs:
                    parameters:
                    - name: api
                    - name: address
                    - name: latitude
                    - name: longitude
                    - name: user_type
                    - name: distance
                    - name: humidity
                    - name: temperature
                    - name: datetime
                    - name: address_name
                  container:
                    image: johnkalogero/notify:v0.1
                    imagePullPolicy: Always
                    command: ["python3", "notify_users.py"]
                    args: ["--api", "{{inputs.parameters.api}}", "--address", "{{inputs.parameters.address}}","--latitude", "{{inputs.parameters.latitude}}", "--longitude", "{{inputs.parameters.longitude}}", "--user_type", "{{inputs.parameters.user_type}}", "--distance", "{{inputs.parameters.distance}}", "--humidity", "{{inputs.parameters.humidity}}", "--temperature", "{{inputs.parameters.temperature}}", "--datetime", "{{inputs.parameters.datetime}}", "--address_name", "{{inputs.parameters.address_name}}"]
                  nodeSelector:
                    location: Peania_Athens_19002
          parameters:
            - src:
                dependencyName: notify1-dep
                dataKey: body.api
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: notify1-dep
                dataKey: body.address
              dest: spec.arguments.parameters.1.value
            - src:
                dependencyName: notify1-dep
                dataKey: body.latitude
              dest: spec.arguments.parameters.2.value
            - src:
                dependencyName: notify1-dep
                dataKey: body.longitude
              dest: spec.arguments.parameters.3.value
            - src:
                dependencyName: notify1-dep
                dataKey: body.user_type
              dest: spec.arguments.parameters.4.value
            - src:
                dependencyName: notify1-dep
                dataKey: body.distance
              dest: spec.arguments.parameters.5.value
            - src:
                dependencyName: notify1-dep
                dataKey: body.humidity
              dest: spec.arguments.parameters.6.value
            - src:
                dependencyName: notify1-dep
                dataKey: body.temperature
              dest: spec.arguments.parameters.7.value
            - src:
                dependencyName: notify1-dep
                dataKey: body.datetime
              dest: spec.arguments.parameters.8.value
            - src:
                dependencyName: notify1-dep
                dataKey: body.address_name
              dest: spec.arguments.parameters.9.value