version: "3.7"

services:

  app:
    build: ./app
    container_name: django-dva
    restart: always
    env_file:
      - ./app/kpi_visualization.env
    expose:
      - 8000  # use expose insted of port to expose ports internal between containers and not to the host maschine
    volumes:
      - ./src/cdn_static_root:/src/cdn_static_root
    command: "gunicorn --workers=2 --bind=0.0.0.0:8000 kpi_visualization.wsgi:application"

  nginx:
    image: nginx:1.17
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./src/cdn_static_root:/static
    depends_on:
      - app