prometheus:
  prometheusSpec:
    additionalScrapeConfigs: |
      - job_name: 'sample-pods'
        scrape_interval: 20s
        scrape_timeout: 10s
        static_configs:
          - targets: ['localhost:9090']