apiVersion: v1
kind: Pod
metadata:
  name: testemail
  labels:
    role: myrole
spec:
  containers:
    - name: testemail
      image: dimitrislask/testmail:latest
      ports:
        - name: testemail
          containerPort: 80
          protocol: TCP