apiVersion: v1
kind: Service
metadata:
  labels:
    app: mqtt
  name: mqtt
  namespace: pi-edge
spec:
  ports:
    - name: "9001"
      protocol: TCP
      nodePort: 30009
      port: 9001
      targetPort: 9001
    - name: "1883"
      protocol: TCP
      nodePort: 31883
      port: 1883
      targetPort: 1883
  selector:
    app: mqtt
  type: NodePort
